### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Amirmcir** [Salehalber/Saleh-T2#1]
test mikonim

**Comment by Salehalber** [comment]
Asle Jeslam

**Comment by Amirmcir** [comment]
> Asle Jeslam

goo khori nko

**Comment by Salehalber** [comment]
goo khori boko

**Comment by Amirmcir** [comment]
> goo khori boko

diverrrrrrrrrrrrrrrrrrrrrrrrrrrrtttttttttttttttttttt

**Comment by Salehalber** [comment]
> diverrrrrrrrrrrrrrrrrrrrrrrrrrrrtttttttttttttttttttt

hala berchi ijuri megi divert
